### ISSUE TITLE
False and 0 is represented as empty string

### ISSUE THREAD

**Issue by warmachine2017** [spence-s/human-object-diff#11]
When the value of the token is false or 0, the output shows an empty string.

**Comment by 8BitJonny** [comment]
Jap, also have that problem.
This is due to this condition in the code that checks if the new property value is a truthy value. Anything like false, 0, or null will fail the condition and therefore return an emtpy string

https://github.com/Spence-S/human-object-diff/blob/master/src/sentence/utils/get-new-val.js#L5
